config/routes.rb
Lnb::Application.routes.draw do
  match 'welcome' => 'wedding#welcome'
  match 'our_story' => 'wedding#our_story'
  match 'wedding_party' => 'wedding#wedding_party'
  match 'events' => 'wedding#events'
  match 'venue' => 'wedding#venue'
  match 'hotel' => 'wedding#hotel'
  match 'rsvp' => 'wedding#rsvp'
  match 'rehearsal_rsvp' => 'wedding#rehearsal_rsvp'
  match 'registry' => 'wedding#registry'
  match 'wedpics' => 'wedding#wedpics'
  match 'rsvp_response' => 'wedding#rsvp_response'

  root :to => 'wedding#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wedding_controller.rb
class WeddingController < ApplicationController
  def show
  end

  def our_story
  end

  def bridal_party
  end

  def ceremony
  end

  def reception
  end

  def hotel
  end

  def registry
  end

  def rsvp
  end

  def rehearsal_rsvp
  end

  def wedpics
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wedding_helper.rb
module WeddingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lilly and Bryan's Wedding</title>
<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="outer_container">

	<%= image_tag("lillybryan.jpg", :id => "headline_image") %>

	<table id="menu">
		<tr>
			<th>
				<%= link_to "Welcome", welcome_path, :class => "top_nav" %>
			</th>
			<th>
				&nbsp;&nbsp;<%= link_to "Our Story", our_story_path, :class => "top_nav" %>
			</th>
			<th style="width: 150px">
				<%= link_to "Wedding Party", wedding_party_path, :class => "top_nav" %>
			</th>
			<th>
				<%= link_to "Venue", venue_path, :class => "top_nav" %>&nbsp;&nbsp;
			</th>
			<th>
				&nbsp;&nbsp;<%= link_to "Events", events_path, :class => "top_nav" %>&nbsp;&nbsp;
			</th>
			<th>
				&nbsp;&nbsp;<%= link_to "Hotel", hotel_path, :class => "top_nav" %>&nbsp;&nbsp;
			</th>
			<th>
				&nbsp;&nbsp;<%= link_to "Rsvp", rsvp_path, :class => "top_nav" %>&nbsp;&nbsp;&nbsp;
			</th>			
			<th>
				<%= link_to "Registry", registry_path, :class => "top_nav" %>
			</th>
		</tr>
	</table>

	<div id="content_container">

	<%= yield %>

	</div>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37628518-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

app/views/wedding/events.html.erb
<br>
<div id="interior_content">
<h1>March 23, 2013</h1>
<hr>
<h3 class="event_header">Ceremony</h3>
Time: 4:00pm<br>
Location: Borgia Room, Mezzanine, Landmark Building<br>
<br>
<h3 class="event_header">Cocktails</h3>
Time: 5:00pm<br>
Location: Grand Ballroom Foyer and Italian Room, Mezzanine, Landmark Building
<br>
<br>
<h3 class="event_header">Group Picture</h3>
Time: 5:50pm<br>
Location: Colonial Room, Mezzanine, Landmark Building
<br>
<br>
<h3 class="event_header">Reception</h3>
Time: 6:00pm<br>
Location: Alexandra's, 32nd Floor, Tower Building<br>
<br>
<br>
<br>
<h1>March 24, 2013</h1>
<hr>
<h3 class="event_header">Light Brunch</h3>
Time: 10:00am<br>
Location: Chairman's Suite, 3rd Floor, Landmark Building<br>

app/views/wedding/hotel.html.erb
<div id="interior_content">
<br>
<h3 class="fancy">Hotel Accommodations</h3>
<b>Westin St. Francis</b><br>
335 Powell St.<br>
San Francisco, CA 94102<br>
(415) 397-7000<br>
<a href="http://www.westinstfrancis.com/">www.westinstfrancis.com</a>
<br><br>
We've reserved a block of rooms at the Westin for $219 per night for reservations that are made prior to 2/23/2012. To make a hotel reservation, please call 1-800-WESTIN1 (1-800-937-8461) and let them know that you'll be a part of the Lilly Ly/Bryan Vu Wedding. The rates do vary, so we recommend that you also check <a href="http://www.starwoodhotels.com/westin/rates/calendar.html?sortOrder=&propertyId=1010&refPage=predecider&accessible=&ctx=search&priceMin=&priceMax=&bedType=&currencyCode=&ES=Thayer_WI-STFRANCIS_1010&nonSmoking=">Westin's site</a> to see if better rates are available.
<br>
<br>
<br>
<h3 class="fancy">Alternate Accommodations</h3>
There are quite a few hotels located in and around the Union Square area. We've listed a few below. Also, the Westin St. Francis is located about two blocks from the Powell Street BART, Muni and Cable Car stops. Many hotels in San Francisco will have convienient access to Union Square via public transportation.<br>
<br>
<br>
<b>Sir Francis Drake Hotel</b><br>
450 Powell Street<br>
San Francisco, CA<br>
(415) 392-7755<br>
<a href="http://www.sirfrancisdrake.com">www.sirfrancisdrake.com</a><br>
<br>
<b>Hilton San Francisco Union Square</b><br>
333 O'Farrell Street<br>
San Francisco, CA 94102<br>
(415) 771-1400<br>
<a href="http://www3.hilton.com/en/hotels/california/hilton-san-francisco-union-square-SFOFHHH/index.html?009=p&008=&007=Search&006=9217371902&002=0022144778021606732&WT.srch=1&012=hiltonsanfranciscounionsquare">www.hilton.com</a><br>
<br>
<b>Parc 55 Wyndham San Francisco - Union Square</b><br>
55 Cyril Magnin Street<br>
San Francisco, CA<br>
(415) 392-8000<br>
<a href="http://www.parc55hotel.com">www.parc55hotel.com</a><br>
<br>
<br>
</div>

app/views/wedding/our_story.html.erb
<div id="interior_content">
<br>
<h3 class="fancy">Our Story</h3>
We randomly ran into each other two Fridays in a row at different happy hours in the Summer of 2011 and have been together ever since. The proposal took place at the top of the Eiffel Tower at around 1:00am on July 7th, 2012, shortly before this picture was taken.
<br>
<br>
<br>
<%= image_tag("eiffel.jpg", :id => "our_story_picture", :width => "500px") %>
<br>
<br>
</div>

app/views/wedding/registry.html.erb
<div id="interior_content">
<br>
<h3 class="fancy">Registry</h3>
<a href="http://www1.bloomingdales.com/registry/wedding/guest/?registryId=173203">Bloomingdale's</a>
<br>
<br>
<a href="http://www.crateandbarrel.com/Gift-Registry/Lilly-Ly-and-Bryan-Vu/r5018385">Crate and Barrel</a>
<br>
<br>
<a href="http://www.honeyfund.com/wedding/lillyandbryan">Honeyfund</a>
<br>
</div>

app/views/wedding/rehearsal_rsvp.html.erb
<div id="interior_content">


<meta itemprop="name" content="Rehearsal RSVP">
<meta itemprop="embedUrl" content="https://docs.google.com/spreadsheet/embeddedform?formkey=dGt3X0c1ck9JNm1XWm1pZjNoU2Z2RFE6MQ">


<br>
<div class="ss-form-container">
<div class="ss-form-heading"><h1 class="ss-form-title">Rehearsal RSVP</h1>
<p></p>


<hr class="ss-email-break" style="display:none;">
<div class="ss-required-asterisk">* Required</div></div>
<br>
<div class="ss-form">

<script type="text/javascript">var submitted=false;</script>
<iframe name="hidden_iframe" id="hidden_iframe"
style="display:none;" onload="if(submitted)
{window.location='/rsvp_response';}"></iframe>

<form action="https://docs.google.com/spreadsheet/formResponse?formkey=dGt3X0c1ck9JNm1XWm1pZjNoU2Z2RFE6MQ&amp;ifq" method="post"
target="hidden_iframe" onsubmit="submitted=true;">

<br>
<div class="errorbox-good">
<div class="ss-item ss-item-required ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_0">Name
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_0"></label>
<input type="text" name="entry.0.single" value="" class="ss-q-short" id="entry_0"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item ss-item-required ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_1">Email Address
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_1"></label>
<input type="text" name="entry.1.single" value="" class="ss-q-short" id="entry_1"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item ss-item-required ss-radio"><div class="ss-form-entry"><label class="ss-q-title" for="entry_2">How many people are attending?
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_2"></label>
<ul class="ss-choices"><li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.2.group" value="We are unable to attend" class="ss-q-radio" id="group_2_1">
We are unable to attend</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.2.group" value="1" class="ss-q-radio" id="group_2_2">
1</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.2.group" value="2" class="ss-q-radio" id="group_2_3">
2</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.2.group" value="3" class="ss-q-radio" id="group_2_4">
3</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.2.group" value="4" class="ss-q-radio" id="group_2_5">
4</label></li>
</ul></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-paragraph-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_3">Please feel free to add any additional information or comments. Thanks for your RSVP!
</label>
<label class="ss-q-help" for="entry_3"></label>
<textarea name="entry.3.single" rows="8" cols="75" class="ss-q-long" id="entry_3"></textarea></div></div></div>
<br>
<input type="hidden" name="pageNumber" value="0">
<input type="hidden" name="backupCache" value="">


<div class="ss-item ss-navigate"><div class="ss-form-entry">
<input type="submit" name="submit" value="Submit" id="submit"></div></div></form>
<script type="text/javascript">
      
      (function() {
var divs = document.getElementById('ss-form').
getElementsByTagName('div');
var numDivs = divs.length;
for (var j = 0; j < numDivs; j++) {
if (divs[j].className == 'errorbox-bad') {
divs[j].lastChild.firstChild.lastChild.focus();
return;
}
}
for (var i = 0; i < numDivs; i++) {
var div = divs[i];
if (div.className == 'ss-form-entry' &&
div.firstChild &&
div.firstChild.className == 'ss-q-title') {
div.lastChild.focus();
return;
}
}
})();
      </script></div></div></div>


</div>

app/views/wedding/rsvp.html.erb
<div id="interior_content">


<meta itemprop="name" content="RSVP">
<meta itemprop="embedUrl" content="https://docs.google.com/spreadsheet/embeddedform?formkey=dHBmVFpYUXlRcjRGMXNadXE4Z3kzRHc6MQ">


<br>
<div class="ss-form-container">
<div class="ss-form-heading"><h3 class="fancy">RSVP</h3>
<p></p>

<hr class="ss-email-break" style="display:none;">
<div class="ss-required-asterisk">* Required</div></div>
<br>
<div class="ss-form">
<script type="text/javascript">var submitted=false;</script>
<iframe name="hidden_iframe" id="hidden_iframe"
style="display:none;" onload="if(submitted)
{window.location='/rsvp_response';}"></iframe>

<form action="https://docs.google.com/spreadsheet/formResponse?formkey=dHBmVFpYUXlRcjRGMXNadXE4Z3kzRHc6MQ&amp;ifq" method="post"
target="hidden_iframe" onsubmit="submitted=true;">

<br>
<div class="errorbox-good">
<div class="ss-item ss-item-required ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_0">Name
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_0"></label>
<input type="text" name="entry.0.single" value="" class="ss-q-short" id="entry_0"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_8">Email Address
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_8"></label>
<input type="text" name="entry.8.single" value="" class="ss-q-short" id="entry_8"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item ss-item-required ss-select"><div class="ss-form-entry"><label class="ss-q-title" for="entry_1">How many people are attending?
<span class="ss-required-asterisk">*</span></label>
<label class="ss-q-help" for="entry_1">Include all adults and children who will attend. If you are not attending, you can skip the rest of the questions.</label>
<select name="entry.1.single" id="entry_1"><option value="We are unable to attend">We are unable to attend</option> <option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option></select></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-select"><div class="ss-form-entry"><label class="ss-q-title" for="entry_2">How many children will attend the wedding?
</label>
<label class="ss-q-help" for="entry_2"></label>
<select name="entry.2.single" id="entry_2"><option value="0">0</option> <option value="1">1</option> <option value="2">2</option> <option value="3">3</option></select></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_3">If you are bringing a guest, what is his or her name?
</label>
<label class="ss-q-help" for="entry_3">We&#39;ll use this for the name cards. If you don&#39;t know at this time, you can email us later.</label>
<input type="text" name="entry.3.single" value="" class="ss-q-short" id="entry_3"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-radio"><div class="ss-form-entry"><label class="ss-q-title" for="entry_4">Which hotel are you staying at?
</label>
<label class="ss-q-help" for="entry_4"></label>
<ul class="ss-choices"><li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.4.group" value="We are not staying at a hotel" class="ss-q-radio" id="group_4_1">
We are not staying at a hotel</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.4.group" value="Westin St. Francis" class="ss-q-radio" id="group_4_2">
Westin St. Francis</label></li>
<li class="ss-choice-item"><input type="radio" name="entry.4.group" value="__option__" class="ss-q-radio" id="other_option:4">
<label for="other_option:4">Other:</label>
<input type="text" name="entry.4.group.other_option_" value="" class="ss-q-other"></li></ul></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-radio"><div class="ss-form-entry"><label class="ss-q-title" for="entry_9">Which meal do you prefer?
</label>
<label class="ss-q-help" for="entry_9"></label>
<ul class="ss-choices"><li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.9.group" value="Beef" class="ss-q-radio" id="group_9_1">
Beef</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.9.group" value="Fish" class="ss-q-radio" id="group_9_2">
Fish</label></li> <li class="ss-choice-item"><label class="ss-choice-label"><input type="radio" name="entry.9.group" value="Vegetarian" class="ss-q-radio" id="group_9_3">
Vegetarian</label></li>
</ul></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_5">Do you have any dietary restrictions we should know about?
</label>
<label class="ss-q-help" for="entry_5">(e.g. vegetarian)</label>
<input type="text" name="entry.5.single" value="" class="ss-q-short" id="entry_5"></div></div></div>
<br> <div class="errorbox-good">
<div class="ss-item  ss-paragraph-text"><div class="ss-form-entry"><label class="ss-q-title" for="entry_6">Please feel free to add any additional information or comments. Thanks for your RSVP!
</label>
<label class="ss-q-help" for="entry_6"></label>
<textarea name="entry.6.single" rows="8" cols="75" class="ss-q-long" id="entry_6"></textarea></div></div></div>
<input type="hidden" name="pageNumber" value="0">
<input type="hidden" name="backupCache" value="">


<div class="ss-item ss-navigate"><div class="ss-form-entry">
<input type="submit" name="submit" value="Submit" id="submit"></div></div></form>
<br>
<br>
<br>
<script type="text/javascript">
      
      (function() {
var divs = document.getElementById('ss-form').
getElementsByTagName('div');
var numDivs = divs.length;
for (var j = 0; j < numDivs; j++) {
if (divs[j].className == 'errorbox-bad') {
divs[j].lastChild.firstChild.lastChild.focus();
return;
}
}
for (var i = 0; i < numDivs; i++) {
var div = divs[i];
if (div.className == 'ss-form-entry' &&
div.firstChild &&
div.firstChild.className == 'ss-q-title') {
div.lastChild.focus();
return;
}
}
})();
      </script></div>
</div></div>


</div>

app/views/wedding/rsvp_response.html.erb
<div id="interior_content">
	<br>
	<br>
	<p id="welcome_paragraph">Your response has been recorded. We'll be emailing you with confirmation shortly. Thanks for your RSVP!</p>
</div>

app/views/wedding/venue.html.erb
<div id="interior_content">
<%= image_tag("st_francis.jpg", :width => "630px") %></center>
<br>
<br>
<br>
<b>Westin St. Francis</b><br>
335 Powell St.<br>
San Francisco, CA 94102<br>
(415) 397-7000<br>
<a href="http://www.westinstfrancis.com/">www.westinstfrancis.com</a><br>
<br>
<br>
<br>
<iframe width="630" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q
&amp;source=s_q
&amp;hl=en
&amp;geocode=
&amp;q=The+Westin+St+Francis,+Powell+Street,+San+Francisco,+CA
&amp;aq=0
&amp;oq=westin+
&amp;sll=37.752258,-122.437477
&amp;sspn=0.131655,0.208054
&amp;ie=UTF8
&amp;hq=The+Westin+St+Francis,+Powell+Street,+San+Francisco,+CA
&amp;t=m
&amp;ll=37.787742,-122.408423
&amp;spn=0.01187,0.021458
&amp;z=14
&amp;iwloc=null
&amp;output=embed"></iframe><br /><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=The+Westin+St+Francis,+Powell+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=westin+&amp;sll=37.752258,-122.437477&amp;sspn=0.131655,0.208054&amp;ie=UTF8&amp;hq=The+Westin+St+Francis,+Powell+Street,+San+Francisco,+CA&amp;t=m&amp;ll=37.787742,-122.408423&amp;spn=0.01187,0.021458&amp;z=15&amp;iwloc=A" style="color: #6B5D52;text-align:left">View Larger Map</a>
<br>
<br>
<br>
<h3 class="fancy">Flights</h3>
San Francisco (SFO) and Oakland (OAK) airports are both about 45 minutes away from the wedding location by car. BART also serves both <a href="http://www.bart.gov/guide/airport/inbound_sfo.aspx">SFO</a> and <a href="http://www.bart.gov/guide/airport/inbound_oak.aspx">OAK</a> with trains running to the Powell Street Station.
<br>
<br>
<h3 class="fancy">Driving Directions</h3>
<b>From East:</b>  Take Route 580 and cross the Bay Bridge, to the Fremont Street Exit on the right. Turn left onto Howard Street, and proceed 4 blocks to 3rd Street. Go right on 3rd Street and cross Market Street. Turn left onto Geary Street until you cross Powell Street. The Westin St. Francis "carriage entrance" is located on Geary, a half block past Powell Street.   <br>
<br>
<b>From San Francisco International Airport:</b> Take 101 North heading towards Highway 80 East/Bay Bridge and exit at 4th Street. Exit right onto Bryant and continue 1 block and turn left onto 3rd Street. Cross the Market Street intersection, and turn left onto Geary Street. The hotel is located just past Union Square, and The Westin St. Francis "carriage entrance" is located on Geary Street, a half block past Powell Street.  <br><br>

<b>From the Golden Gate Bridge (North):</b>  Cross the bridge and exit at Lombard Street. Turn right onto Van Ness, and left onto Bush. Turn right onto Powell, then make another right onto Geary Street. The Westin St. Francis "carriage entrance" is right off of Geary Street.

<br>
<br>
<h3 class="fancy">Parking Options</h3>
Garage Parking is available on-site at $40 for guests not staying overnight. The overnight rate is $51 + tax per night per car with in and out privileges. Nearby lots with lower rates are also linked below.
<br>
<br>
<a href="http://www.westinstfrancis.com/var/cdev_base/storage/original/application/44e375d524866b90592c675ae93fc9fb.pdf">Other Parking Options</a>

app/views/wedding/wedding_party.html.erb
<div id="interior_content">
<br>
<h3 class="fancy">Wedding Party</h3>
<br>
<table id="wedding_party_table">
	<tr>
		<td class="wedding_party_data" width="350px">
			<span class="wedding_party_header">Maid of Honor</span><br>
			Ennee Ly Ngoon, sister of the Bride<br>
			<br>

			<span class="wedding_party_header">Bridesmaids</span><br>
			Emly Ly, cousin of the Bride<br>
			Lyna Thoeun, cousin of the Bride<br>
			<br>

			<span class="wedding_party_header">Flower Girls</span><br>
			Karen Heng, first cousin once removed of the Bride<br>
			Zyriah Thoeun, first cousin once removed of the Bride<br>
			<br>

			<span class="wedding_party_header">Bride's Escort</span><br>
			Nam Ly, father of the Bride<br>
		</td>
		<td width="20px">
			&nbsp;
		</td>
		<td class="wedding_party_data">
			<span class="wedding_party_header">Best Man</span><br>
			Daniel Vu, brother of the Groom<br>
			<br>

			<span class="wedding_party_header">Groomsmen</span><br>
			Noah Ruderman, friend of the Groom<br>
			Washington Miguel, friend of the Groom<br>
			Scott Wiener, friend of the Groom<br>
			<br>
			<span class="wedding_party_header">Ring Bearer</span><br>
			Ethan Dawson, cousin of the Bride<br>
			<br>

			<span class="wedding_party_header">Officiant</span><br>
			Tasha Castaneda, friend of the Bride<br>
			<br>
		</td>
	</tr>
</table>
</div>

app/views/wedding/wedpics.html.erb
<div id="interior_content">

<%= image_tag("poster.png", :width => "600px") %>

</div>

app/views/wedding/welcome.html.erb
<div id="interior_content">
<br>
<%= image_tag("bryannlilly.jpg", :id => "main_photo") %>
<br>
<br>
<p id="welcome_paragraph">Welcome! We are delighted to be celebrating our wedding with our family and friends. For more information on events, locations, accommodations, etc. please click the links above.</p>
<div id="welcome_body_text">
Also, all guests attending are invited to help us capture the wedding day with your own pictures using <%= link_to "WedPics", wedpics_path, :class => "wed_pics" %>!
	<ul type="square">
		<li>
			Download the FREE iPhone or Android App
		</li>
		<li>
			Use our access code, <b>LillyBryan</b>, to join our wedding album and share all your pictures you take all weekend!
		</li>
		<li>
			You can also upload pictures after the wedding on  <a href="http://www.wedpics.com" class="wed_pics">wedpics.com</a>.
		</li>
	</ul>
If you have any questions, please e-mail us at
<a href="mailto:bryanvu@gmail.com">bryanvu@gmail.com</a> or <a href="mailto:lillyly@gmail.com">lillyly@gmail.com</a>.<br>
<br>
<br>
Sincerely,
<p class="names">Lilly & Bryan</p>
<br>

</div>
</div>